import React, { useEffect, useState } from "react";
import { get } from "lodash";
import LoadingImages from "../../../LoadingImages";

import { getPreviewBulk } from "../../../../services/ajax/current-bulk";

//@ts-ignore
const { __ } = wp.i18n;

const ViewDataBulk = ({ state }) => {
	const [loading, setLoading] = useState(true);
	const [images, setImages] = useState([]);

	useEffect(() => {
		const fetchData = async () => {
			const { data } = await getPreviewBulk();

			setLoading(false);
			setImages(data);
		};

		fetchData();
	}, []);

	const optimizeFilename = get(
		state,
		"currentProcess.settings.optimizeFile",
		false
	);

	return (
		<div className="bg-white rounded-lg border max-w-5xl p-6 relative">
			<h2 className="text-base font-bold">
				{__("Results details", "imageseo")}
			</h2>
			<p className="text-sm my-2">
				{__(
					"Here is the preview of 5 randoms alt tags generated by our AI.  You can manually edit them in the WordPress media library.",
					"imageseo"
				)}
			</p>
			<div className="mt-2">
				{loading && <LoadingImages />}
				{images.map((image, key) => {
					let filename = __("Sorry, no filename found", "imagesee");
					let alt = "";
					if (get(image, "report.success")) {
						filename = `${get(image, "report.filename")}.${get(
							image,
							"report.extension"
						)}`;
						alt = `${get(image, "report.alt")}`;
					}
					return (
						<div className="flex items-center mb-4" key={key}>
							<div className="p-2 border rounded-lg mr-4">
								<img src={image.url} className="w-16 h-16" />
							</div>
							<div>
								{optimizeFilename && (
									<p className="text-sm">
										{__("Filename alias:", "imageseo")}{" "}
										{filename}
									</p>
								)}

								<p className="text-sm">
									{__("Alt:", "imageseo")} {alt}
								</p>
							</div>
						</div>
					);
				})}
			</div>
		</div>
	);
};

export default ViewDataBulk;
